### ISSUE TITLE
Issue with sar-u section in parsepbuttons on AIX7.2 + Cache 2017.2

### ISSUE THREAD

**Issue by d-little** [murrayo/yape#18]
Figured I'd raise an issue for this.

Running: ```docker container run --rm -v "c:\temp\pbuttons":/data/ yape/yape /data/pbuttons.html```
```
Traceback (most recent call last):
  File "/usr/local/bin/yape", line 11, in <module>
    load_entry_point('yape', 'console_scripts', 'yape')()
  File "/src/yape/yape/command_line.py", line 6, in main
    yape.yape2()
  File "/src/yape/yape/main.py", line 165, in yape2
    parsepbuttons(args.pButtons_file_name,db)
  File "/src/yape/yape/parsepbuttons.py", line 541, in parsepbuttons
    cursor.execute(insertquery, cols)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 5 supplied.
```

This is the sar-u section in the pbuttons html where it is crashing out:
```
 29      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0   0.0 100.0   0.0   0.0   0.0   0.0      0   0.0   0.4   0.0  99.6  0.00   0.0      0      0 100.0   0.0   0.0
 30      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0   0.0 100.0   0.0   0.0   0.0   0.0      0   0.0   0.4   0.0  99.6  0.00   0.0      0      0 100.0   0.0   0.0
 31      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0   0.0 100.0   0.0   0.0   0.0   0.0      0   0.0   0.4   0.0  99.6  0.00   0.0      0      0 100.0   0.0   0.0
ALL   6090      0      0      0    963     40   4954      0   8620   2353      4      5      0      0      0  98.2   0.2   0.0   1.6   0.0   0.0  62476  52.4   6.3   0.4  40.9  2.21 147.7    226   2736 100.0   0.0   0.0
</pre><p align="right"><font size="3"><a href="#Topofpage">Back to top</a></font></p><hr size="4" noshade><b><font face="Arial, Helvetica, sans-serif" size="4" color="#0000FF"><div id=sar-u></div>sar -u</font></b><br><!-- beg_sar_u --><pre>
AIX HOSTNAME 2 7 REDACTED    04/22/19
System configuration: lcpu=8 ent=1.0 mode=Uncapped 
00:00:24    %usr    %sys    %wio   %idle   physc   %entc
00:00:34      22       2       1      75    0.72    48.3
00:00:44      24       3       1      72    0.71    47.4
00:00:54      24       2       1      72    0.72    47.7
00:01:04      31       6       1      62    1.07    71.6
```

**Comment by kazamatzuri** [comment]
it would be nice to have access to the offending pbuttons.html to be able to debug this further. I suspect it's choking about not properly detecting the end of the section?

**Comment by kazamatzuri** [comment]
closing as no data available to debug
